"""
memory.py
----------
Manages conversation memory: stores raw chat turns and maintains
a running summary (generated by Mixtral) so token usage stays low
across a long conversation.
"""


class ConversationMemory:
    def __init__(self):
        self.raw_history: list[dict] = []   # [{"role": "user"/"assistant", "content": ...}, ...]
        self.summary: str = ""              # running summary of older turns

    def add_turn(self, role: str, content: str):
        self.raw_history.append({"role": role, "content": content})

    def get_recent_turns(self, n: int = 4) -> list[dict]:
        """Return the last n raw turns (for display or lightweight context)."""
        return self.raw_history[-n:]

    def get_summary(self) -> str:
        return self.summary

    def update_summary(self, new_summary: str):
        """Called after Mixtral produces a fresh condensed summary of the conversation."""
        self.summary = new_summary

    def get_full_history_text(self) -> str:
        """Flatten raw history into plain text (useful for display in an expandable panel)."""
        lines = []
        for turn in self.raw_history:
            prefix = "User" if turn["role"] == "user" else "Assistant"
            lines.append(f"{prefix}: {turn['content']}")
        return "\n".join(lines)

    def reset(self):
        self.raw_history = []
        self.summary = ""